// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'Insert api key here',
    appId: '1:956410528518:web:11c8b413b642e198881487',
    messagingSenderId: '956410528518',
    projectId: 'fase8growdev',
    authDomain: 'fase8growdev.firebaseapp.com',
    storageBucket: 'fase8growdev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'insert api key here',
    appId: '1:956410528518:android:cae1b285611e28bf881487',
    messagingSenderId: '956410528518',
    projectId: 'fase8growdev',
    storageBucket: 'fase8growdev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'Insert api key here',
    appId: '1:956410528518:ios:d941fb3dd1a2452a881487',
    messagingSenderId: '956410528518',
    projectId: 'fase8growdev',
    storageBucket: 'fase8growdev.appspot.com',
    iosBundleId: 'com.example.socialLoginNotificationFase8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'Insert api key here',
    appId: '1:956410528518:ios:d941fb3dd1a2452a881487',
    messagingSenderId: '956410528518',
    projectId: 'fase8growdev',
    storageBucket: 'fase8growdev.appspot.com',
    iosBundleId: 'com.example.socialLoginNotificationFase8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'Insert api key here',
    appId: '1:956410528518:web:fa2060174cee3c93881487',
    messagingSenderId: '956410528518',
    projectId: 'fase8growdev',
    authDomain: 'fase8growdev.firebaseapp.com',
    storageBucket: 'fase8growdev.appspot.com',
  );
}
